### ISSUE TITLE
total_params question

### ISSUE THREAD

**Issue by GreenWindow1997** [ziplab/SPT#8]
In line279 of engine.py, why is the ratio calculated as follows: total_params = (unstructured_param_num + structured_param_num + 768) / 1e6? What does 1e6 represent, and why is there a 768?

**Comment by Charleshhy** [comment]
Hi,

Thanks for your interest in your work! 768 is the hidden dimension of ViT-B models. Here is the bias term in the last linear layer (classification head) and 1e6 is the number of 1M parameters.
